# -*- coding: utf-8 -*-
"""function_filter_list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EN2QNP5G4x3GWzTaP-991H8lyWNuPAwX
"""

def filter_by_threshold(numbers, threshold) :
  result = []
  for num in numbers :
    if num <= threshold :
      result.append(num)
  return result

numbers = [3, 15, 8, 22, 1, 30, 7, 19]
threshold = 10
filtered = filter_by_threshold(numbers, threshold)
print(filtered)