# -*- coding: utf-8 -*-
"""recursive_inner_plus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EN2QNP5G4x3GWzTaP-991H8lyWNuPAwX
"""

def find_innermost_list(lst) :
  for item in lst:
    if isinstance(item, list) :
      return find_innermost_list(item)
  return lst

def add_one_to_each(lst) :
  if len(lst) == 0 :
    return []
  return [lst[0] + 1] + add_one_to_each(lst[1:])

def innermost_plus_one(lst) :
  innermost = find_innermost_list(lst)
  return add_one_to_each(innermost)

input_list = [1, 2, 3, 4, [5, 6, 7, [8, 9]]]
print(innermost_plus_one(input_list))