# -*- coding: utf-8 -*-
"""while_inner_plus.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EN2QNP5G4x3GWzTaP-991H8lyWNuPAwX
"""

import sys
import ast

def find_innermost_list(lst) :
  current = lst
  while True :
    found = None
    i = 0
    while i < len(current) :
      if isinstance(current[i], list) :
        found = current[i]
        break
      i += 1
    if found is None :
      break
    current = found
  return current

def add_one_to_each(lst) :
  result = []
  i = 0
  while i < len(lst) :
    result.append(lst[i] + 1)
    i += 1
  return result

def innermost_plus_one(lst) :
  innermost = find_innermost_list(lst)
  return add_one_to_each(innermost)

input_list = [1, 2, 3, 4, [5, 6, 7, [8,9]]]
print(innermost_plus_one(input_list))